language: python
env:
    - TOXENV=py27-django19
    - TOXENV=py27-django110
    - TOXENV=py34-django19
    - TOXENV=py34-django110
    - TOXENV=py35-django19
    - TOXENV=py35-django110
install:
    - travis_retry pip install tox
script:
    - travis_retry tox
